netsh advfirewall firewall show rule name=all | findstr Microsoft.Windows.Cortana | %{ $fwout=$_.Split('@')[1]; }; Set-NetFirewallRule -Group "@$fwout" -Action block
netsh advfirewall firewall show rule name=all | findstr Microsoft.Windows.Photos | %{ $fwout=$_.Split('@')[1]; }; Set-NetFirewallRule -Group "@$fwout" -Action block
netsh advfirewall firewall show rule name=all | findstr Microsoft.WindowsFeedback | %{ $fwout=$_.Split('@')[1]; }; Set-NetFirewallRule -Group "@$fwout" -Action block
netsh advfirewall firewall show rule name=all | findstr Microsoft.Windows.CloudExperienceHost | %{ $fwout=$_.Split('@')[1]; }; Set-NetFirewallRule -Group "@$fwout" -Action block
netsh advfirewall firewall show rule name=all | findstr Microsoft.WindowsReadingList | %{ $fwout=$_.Split('@')[1]; }; Set-NetFirewallRule -Group "@$fwout" -Action block
netsh advfirewall firewall show rule name=all | findstr Microsoft.WindowsMaps | %{ $fwout=$_.Split('@')[1]; }; Set-NetFirewallRule -Group "@$fwout" -Action block
netsh advfirewall firewall show rule name=all | findstr Microsoft.AccountsControl | %{ $fwout=$_.Split('@')[1]; }; Set-NetFirewallRule -Group "@$fwout" -Action block
netsh advfirewall firewall show rule name=all | findstr Microsoft.BingFinance | %{ $fwout=$_.Split('@')[1]; }; Set-NetFirewallRule -Group "@$fwout" -Action block
netsh advfirewall firewall show rule name=all | findstr Microsoft.BingFoodAndDrink | %{ $fwout=$_.Split('@')[1]; }; Set-NetFirewallRule -Group "@$fwout" -Action block
netsh advfirewall firewall show rule name=all | findstr Microsoft.BingHealthAndFitness | %{ $fwout=$_.Split('@')[1]; }; Set-NetFirewallRule -Group "@$fwout" -Action block
netsh advfirewall firewall show rule name=all | findstr Microsoft.BingNews | %{ $fwout=$_.Split('@')[1]; }; Set-NetFirewallRule -Group "@$fwout" -Action block
netsh advfirewall firewall show rule name=all | findstr Microsoft.BingSports | %{ $fwout=$_.Split('@')[1]; }; Set-NetFirewallRule -Group "@$fwout" -Action block
netsh advfirewall firewall show rule name=all | findstr Microsoft.LockApp | %{ $fwout=$_.Split('@')[1]; }; Set-NetFirewallRule -Group "@$fwout" -Action block
netsh advfirewall firewall show rule name=all | findstr Microsoft.Music | %{ $fwout=$_.Split('@')[1]; }; Set-NetFirewallRule -Group "@$fwout" -Action block
netsh advfirewall firewall show rule name=all | findstr Microsoft.People | %{ $fwout=$_.Split('@')[1]; }; Set-NetFirewallRule -Group "@$fwout" -Action block
netsh advfirewall firewall show rule name=all | findstr Microsoft.Video | %{ $fwout=$_.Split('@')[1]; }; Set-NetFirewallRule -Group "@$fwout" -Action block
netsh advfirewall firewall show rule name=all | findstr Microsoft.XboxGameCallableUI | %{ $fwout=$_.Split('@')[1]; }; Set-NetFirewallRule -Group "@$fwout" -Action block
netsh advfirewall firewall show rule name=all | findstr Microsoft.XboxLIVEGames | %{ $fwout=$_.Split('@')[1]; }; Set-NetFirewallRule -Group "@$fwout" -Action block
netsh advfirewall firewall show rule name=all | findstr Microsoft.ZuneMusic | %{ $fwout=$_.Split('@')[1]; }; Set-NetFirewallRule -Group "@$fwout" -Action block
netsh advfirewall firewall show rule name=all | findstr Microsoft.ZuneVideo | %{ $fwout=$_.Split('@')[1]; }; Set-NetFirewallRule -Group "@$fwout" -Action block
